apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-af
  labels:
    app: mlops-af
spec:
  replicas: 1
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  selector:
    matchLabels:
      app: mlops-af
  template:
    metadata:
      labels:
        app: mlops-af
    spec:
      volumes:
        - name: sources-root
          emptyDir: {}
        - name: nginx-conf
          emptyDir: {}
      initContainers:
        - name: prepare-src
          image: python:3.7
          env:
            - name: GIT_REPO
              value: https://github.com/artemlops/awful-mlops.git
          volumeMounts:
            - name: sources-root
              mountPath: /var/www/mlops.af/public
            - name: nginx-conf
              mountPath: /etc/nginx
          command:
            - "/bin/bash"
            - "-euo"
            - "xtrace"
            - "-c"
            - >-
              pip install markdown==2.6.11
              && cd $(mktemp -d)
              && git clone ${GIT_REPO} ./repo
              && cd ./repo
              && python site/build.py --in_md README.md --in_html_template site/template.html --out_html site/www/index.html
              && cp -r site/img -T /var/www/mlops.af/public
              && cp site/nginx.conf /etc/nginx/nginx.conf
      containers:
        - name: server
          image: nginx:1.19.7
          volumeMounts:
            - name: sources-root
              mountPath: /var/www/mlops.af/public
            - name: nginx-conf
              mountPath: /etc/nginx
          livenessProbe:
            httpGet:
              path: /
              port: 8080
