apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: mlops-af
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: mlops-af-ingress
spec:
  tls:
  - hosts:
      - mlops.af
    secretName: echo-tls
  rules:
  - host: mlops.af
    http:
      paths:
      - path: /
        backend:
          serviceName: mlops-af-proxy
          servicePort: 80
