apiVersion: v1
kind: Namespace
metadata:
  name: mlops-af
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mlops-af
  name: nginx
data:
  nginx.conf: |
    events {
      worker_connections  4096;  ## Default: 1024
    }
    http {
      server {
        listen 8080;
        server_name artemlops.github.io;
        location / {
          proxy_pass https://artemlops.github.io/awful-mlops/;
        }
      }
    }
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: mlops-af
  name: mlops-af-proxy
  labels:
    app: mlops-af
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-af
  template:
    metadata:
      labels:
        app: mlops-af
    spec:
      containers:
        - name: server
          image: nginx:1.19.7
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx
          ports:
          - containerPort: 8080
      volumes:
        - name: nginx-config
          configMap:
            name: nginx
---
kind: Service
apiVersion: v1
metadata:
  namespace: mlops-af
  name: mlops-af-proxy
spec:
  selector:
    app: mlops-af
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: mlops-af
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: mlops-af-proxy
spec:
  tls:
  - hosts:
      - mlops.af
    secretName: echo-tls
  rules:
  - host: mlops.af
    http:
      paths:
      - path: /
        backend:
          serviceName: mlops-af-proxy
          servicePort: 80
